package com.ai.SpringAIProject.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Meal Plan Entity - Stores high-level plan metadata
 * 
 * Represents a user's active medical meal plan with associated conditions
 * and duration. Links to multiple daily meal entries.
 */
@Entity
@Table(name = "meal_plans")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MealPlan {
    
    @Id
    @Column(name = "plan_id", length = 50)
    private String planId;  // Generated by Python: "PLAN_20260115_143022"
    
    @Column(name = "user_id", nullable = false)
    private Long userId;  // FK to users table (will add @ManyToOne later)
    
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "conditions", columnDefinition = "jsonb")
    private List<String> conditions;  // ["diabetes_type2", "hypertension"]
    
    @Column(name = "duration_days", nullable = false)
    private Integer durationDays;
    
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;
    
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;
    
    @Column(name = "is_active")
    private Boolean isActive = true;  // Soft delete flag
    
    @Column(name = "summary", columnDefinition = "TEXT")
    private String summary;  // "30-day diabetes meal plan"
    
    @Column(name = "total_days_completed")
    private Integer totalDaysCompleted = 0;  // For progress tracking
    
    @Column(name = "created_at", updatable = false)
    private LocalDate createdAt;
    
    @Column(name = "updated_at")
    private LocalDate updatedAt;
    
    // Relationship: One Plan has Many Days
    @OneToMany(mappedBy = "mealPlan", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<MealPlanDay> days = new ArrayList<>();
    
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDate.now();
        updatedAt = LocalDate.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDate.now();
    }
    
    // Helper method to add a day to this plan
    public void addDay(MealPlanDay day) {
        days.add(day);
        day.setMealPlan(this);
    }
}
